use_frameworks!

target 'simplifycommerce_Example' do
  pod 'simplifycommerce', :path => '../simplifycommerce.podspec'

  target 'simplifycommerce_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
