source 'https://cdn.cocoapods.org/'
source 'https://github.com/allanwang0201/privtePods.git'
use_frameworks!

platform :ios, '12.1'

target 'simplifycommerce_Example' do
  pod 'simplifycommerce', '~> 0.1.2'

  target 'simplifycommerce_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
